name: CoreAPI
version: ${version}
main: io.rhythmknights.coreapi.CoreAPI
description: ${description}
api-version: 1.13
authors: [RhythmKnights]
website: https://github.com/rhythmknights/CoreAPI

commands:
  coreapi:
    description: CoreAPI admin commands
    usage: /coreapi
    permission: coreapi.admin

permissions:
  coreapi.admin:
    description: Gives access to all CoreAPI commands
    default: op